java-subway-map-implementation
kth496/java-subway-map-implementation pull request #3
Opened 2022-03-25 12:53 UTC by eunbii0213

선생님! 소스코드 모두 작성 완료하였습니다! 피드백 부탁드립니다!

2022-03-25 19:17 UTC, kth496 requested changes
@eunbii0213 현재 프로그램 기능이 완벽한 상태가 아니라 간단한 리뷰만 남겼습니다. 참고해서 수정해주시고 다시 요청주세요!

2022-03-25 19:17 UTC, kth496 commented on src/main/java/subway/Application.java
> +        StationRepository stationRepository = new StationRepository();
이 두 레포지토리 클래스는 `static`메서드만 존재합니다. 즉 유틸리티성 클래스라는 것인데, 이 경우에는 생성자로 별도의 객체를 생성할 필요가 없습니다. 불필요한 객체 생성을 하지 않는 것이 좋아요. `Section`클래스도 동일합니다.

다만, 지금은 생성자에 초기화 로직이 들어가 있어서 바로 제거는 어렵네요. 초기화 로직은 해당 레포지토리들을 사용하기는 하지만, 순전히 앱 관점에서 별도의 초기화 과정일 뿐입니다. 초기화 클래스로 분리하고 생성자를 비우시면 됩니다!

2022-03-25 19:17 UTC, kth496 commented on src/main/java/subway/domain/User.java
> +    }
`input`변수가 필요해보이지 않습니다.

2022-03-25 19:17 UTC, kth496 commented on src/main/java/subway/Application.java
> +    private static void subwayMap(Scanner scanner, Checker checker, LineRepository lineRepository, StationRepository stationRepository, View view, User user) {
한 줄에 너무 많은 코드가 들어가면 읽기 어려워집니다. 컨벤션에 나와있는 항목이니 지켜주세요!

아울러, 현재 전체적으로 컨벤션이 지켜지지 않은 부분이 꽤 있으니 자동 포맷팅도 한번씩 눌러주세요.

2022-03-25 19:17 UTC, kth496 commented on src/main/java/subway/Application.java
> +        }
무한루프로 시작을 했는데 종료 조건이 없네요. 참고로 현재 Q조건을 입력해도 프로그램이 종료되지 않습니다!

2022-03-26 02:57 UTC, eunbii0213 commented
전에 받았던 피드백들(하드코딩하지않기, static method 객체 만들지 않고 사용하기, 컨벤션 지키기, 테스팅 모두 완료하기..)을 반복하지 않으려고 노력하는데 생각보다 쉽지 않네요 😭.. 더 노력해서 완벽히 지켜보도록 하겠습니다!! 친절한 피드백 감사드려요!!

<질문사항>
1. 언급하신 유틸리티 클래스에 대해서 고민해보니 잘 이용하면 매개변수로 넘기는 객체와 생성하는 객체 양을 줄일 수 있어서 코드가 더 깔끔해질 수도 있겠다는 생각을 했습니다! 
LineView, StationView, Checker같은 (굳이 객체를 생성 안 해도 될 것 같은) 클래스들을 유틸리티 클래스로 만들면 더 깔끔해질 것 같기도 한데.. 선생님 생각은 어떠신지 궁금합니다! 괜찮은 접근방법일까요? 

2. Checker class 의 35번째 line의
line.getSubwayMap().size()-1처럼 index와의 비교 때문에(size는 1부터 count, index로 list접근시 0부터 count) size에 -1을 해주는 경우 어떻게 상수를 선언해야할지 잘 감이 잡히지 않습니다. 힌트를 받을 수 있을까요?

3. 저번에 질문했듯이 view 를 상속하여 1. 2. 등과 같은 접두사를 따로 분리하는 방법으로 진행해보려고했습니다..! 그런데 제가 아닌 다른 사람은 문자열이 어떤 값을 가지는지 제대로 확인하고 싶을 때마다 매번 view class를 들어가야하는 게 번거로울 것 같다는 생각도 듭니다. 그래서 일단은 이렇게 구현했는데 선생님의 생각은 어떠신지 궁금합니다!

2022-03-26 09:24 UTC, kth496 commented
@eunbii0213 

1. 넵 유틸리티 관련 클래스들은 모두 static으로 변경하는 방법도 괜찮다고 생각합니다!

2. 아주 좋은 현상입니다! 어떤 리스트의 마지막 요소를 찾아내기 위해서는 반드시 size - 1 의 인덱스로 접근해야하죠. 이는 One 같은 이름으로 분리할수도 없으며, 딱히 이름을 붙이기도 어렵습니다. 지금은 마지막 인덱스를 위한 상수이므로 `LAST_INDEX_CONSTANT` 정도로 붙여볼 수 있겠습니다. 사실 이 방법보다 약간 편리하게 관리하는 법이 있는데요. 이건 화요일에 소개해드릴게요~

3. 넵넵 이 부분은 선택사항입니다. 어떤 정답이 있는 것이 아니라, 관점에 따라 다른 것이지요. 지금은 출력이 엄청 복잡한 구조는 아니니, 접두사 분리는 생략하고 다른 부분에 집중하는게 좋아보입니다!

2022-03-26 09:51 UTC, kth496 requested changes
@eunbii0213 코드 리뷰를 남겼으니 확인해주세요! 참고로, 리뷰 자체의 양은 적지만 수정해야하는 부분은 많으실거에요. 코멘트가 달린 부분말고도 전체 코드에서 피드백받은 내용이 적용될 수 있는 부분을 찾아서 적용해보세요!

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/Checker.java
> +                errorView.userInputError();
`static`메서드에 접근하므로 객체 레퍼런스로 접근하지 말고 클래스명으로 접근해주세요! 아울러 `ErrorView`에는 `static`메서드만 가지고 있으므로 객체 자체를 생성할 필요가 없습니다.

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/Controller.java
> +    public void startSubwayMap(StationView stationView, LineView lineView, View view, SectionView sectionView, String input, Checker checker, Scanner scanner, User user) {
한 줄에 작성할 수 있는 코드의 길이는 컨벤션을 따라주세요. 지금은 너무 길게 작성되어 있습니다.

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/StationView.java
> +    public void showStationMenuGuide() {
어떤 뷰의 출력 메서드는 `static`인데, 또 어떤 경우에는 `non-static`이네요. 이 부분은 의도에 맞게 통일해주세요!

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/Controller.java
> +            getUserInputAgain = checker.checkUserInputIsNotValid(input, STATION_OPTION_START, STATION_OPTION_END, false);
인자로 받은 값을 변경하기보다, 새로운 지역변수를 만들어 사용하시는 편이 읽기에도 좋습니다. 성능면에서 큰 차이도 없구요!

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/Controller.java
> +    public boolean isStationOptionOneError(StationView stationView, Checker checker, User user, Scanner scanner) {
이 메서드는 여러가지 일을 하고 있습니다. 길이가 조건에 맞는지 체크하고, 맞는다면 addStation까지 하고 있지요. 너무 많은 일을 하고 있으며, 이름으로 그 역할이 명확히 표현되지 않습니다. 따라서 이 메서드는 에러나 유효성 검사 로직만 남기시고, 실제로 역을 추가하는 로직은 따로 분리해주세요!

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/domain/Line.java
> +    }
현재 의도대로 동작하지 않는 것 같네요.

맨 처음 초기화가 된 상태로 2호선의 역삼역을 삭제해보세요. 갑자기 다른 역이 역삼역의 자리를 차지하는 것을 확인하실 수 있을겁니다. 구현이 잘못된 부분이니 수정 부탁드립니다!

2022-03-26 09:51 UTC, kth496 commented on src/main/java/subway/domain/Section.java
> +    }
이렇게 작성하기보다 Line에게 메시지를 보내서 직접 추가하게 만드는 편이 좋습니다. 지금은 Line의 멤버 변수를 꺼내서 직접 추가하니, 외부에서 변경될 가능성이 커지고 있습니다. getter로는 오로지 읽을수만 있는 read-only 객체를 반환한다고 생각하고 개선해주세요.

2022-03-27 03:00 UTC, eunbii0213 commented on src/main/java/subway/domain/Line.java
> +    }
지하철 구간 삭제 기능
1. 노선에 등록된 역을 제거할 수 있다.
2. 종점을 제거할 경우 다음 역이 종점이 된다.
3. 노선에 포함된 역이 두개 이하일 때는 역을 제거할 수 없다.

에서 2번문항을 저는 "2호선의 양재역을 제거할 시 종점역은 그 '다음'역인 남부터미널 역으로 설정하라" 로 받아들였는데 제가 잘못 이해한 건가요?! 혹시 양재역이 아니라 강남역이 종점으로 설정 되어야하나요?

2022-03-27 04:13 UTC, eunbii0213 commented
선생님! 말씀대로 언급된 코드 외에 다른 코드도 살펴보며 수정해보았습니다! 피드백 부탁드립니다 🙂

<질문사항>
1. LineRepository class의 addStationsInLine method가 피드백에서 언급한 get method의 read-only를 위반한 것일까요? 조금 헷갈리네요 🥲
2. 역과 노선을 초기화 할 때 하드코딩을 하는 것 같아보입니다. 이렇게 초기화 하는 양이 많을 때도 상수로 빼서 값을 넣어주는 게 좋을까요?

2022-03-27 09:39 UTC, kth496 commented on src/main/java/subway/domain/Line.java
> +    }
@eunbii0213 넵 다음역이라 함은 각 노선에서의 다음 역을 의미합니다. 우리가 일상생활에서 어떤 노선에서 마지막 역이 제거되었다고 한다면, 노선에서 연결된 그 전의 역이 종점으로 다시 설정되지요. 하지만 현재 구현은 등록된 번호 순서상 역삼역 다음이 남부터미널역이고, 그래서 그 다음역을 남부터미널로 생각하신 듯 합니다!

2022-03-27 09:46 UTC, kth496 commented
@eunbii0213 아주 중요한 질문을 해주셨네요! 좋은 방향으로 개선될 조짐이라 생각합니다 😃

> 1. LineRepository class의 addStationsInLine method가 피드백에서 언급한 get method의 read-only를 위반한 것일까요? 조금 헷갈리네요 🥲

해당 메서드가 문제인 것이 아니라 getter가 문제입니다. LineRepository에서 lines 리스트를 그대로 반환하는 getLines() 메서드를 만들어서 호출해서 한번 새로운 라인을 추가해보세요.(리스트니까 add 메서드 사용하시면 됩니다) 그리고나서 원본에 새로운 라인이 추가되었는지도 확인해보세요. 아마 추가가 될겁니다. 왜냐하면 지금 getter에서 원본을 그대로 반환하고 있기 때문입니다. 제가 피드백 드렸던 코드에서는 `line.getSubwayMap().add(...)` 이런 형태였어요. `getSubwayMap()`메서드가 원본을 반환해서 문제가 되었던 부분입니다.

```java
public static List<Line> lines() {
        return Collections.unmodifiableList(lines);
}
```
이 코드가 어떤 역할을 하는지도 공부해보시면 좋습니다!

<br>

> 2. 역과 노선을 초기화 할 때 하드코딩을 하는 것 같아보입니다. 이렇게 초기화 하는 양이 많을 때도 상수로 빼서 값을 넣어주는 게 좋을까요?

넵 앞서 피드백 드린 내용중에 초기화를 위한 별도의 클래스를 만들어달라는 의미가 이것 때문입니다. 사실상 중복되거나 하드코딩되는 값이 `Repository`클래스에는 있을 이유가 없기 때문이죠. 별도로 분리하시고, 상수로 분리하시면 됩니다!

2022-03-29 05:05 UTC, eunbii0213 commented
선생님! 질문사항도 반영하여 코드 수정했습니다! 수업시간에 피드백 부탁드립니다!🙂

2022-03-30 11:00 UTC, eunbii0213 commented
피드백을 반영하여 
1. 방어 logic은 domain 객체에 넣기
2. LineRepository, Line, StationRepository의 list를 반환하는 getter 없애기
3. InitialBeforeStart class의 List들 static 제거 하기
4. Repository에 Initial method 제거하기 
5. 중복된 add Logic 삭제하기
같은 부분들을 수정하였습니다!

InitialBeforeStart class의 List들에 class를 넣었던 이유는, 이 클래스 자체를 유틸리티 클래스를 만들고자함이었습니다. 그러나 피드백을 통해 list에 static이 붙으면 변하는 객체라고 인식됨을 알았고 static을 제거하고 InitialBeforeStart class의 객체를 생성하는 방향으로 잡았습니다!

그리고 항상 코드를 짤 때 (왜인지는 모르겠지만..) 당연히 getter를 써서 '원본'을 가져와서 추가하고, 삭제해야한다고 생각했었는데 그 원본을 가진 class가 아니라면 message만 전달해주고 그 일은 원본이 시키게 한다는 점을 이해하고 코드로 만드는 게 생각보다 어렵게 느껴졌어요😭..! 이 부분을 잘 구현한건지도 언급 부탁드립니다!

2022-04-01 04:23 UTC, eunbii0213 commented
<질문사항> 
선생님! 저번에 설명해주신 도메인 주도 설계를 생각하면서 현재의 class들을 보니 제가 생각했을 때는 domain으로 취급되어야하는 class가 Line, Section, Station뿐인데 현재 Domain패키지에는 InitialBeforeStart, LineRepository등의 class도 같이 들어가있는 것을 확인했습니다! 따로 빼는 게 좋겠죠..?!

2022-04-01 12:56 UTC, kth496 reviewed
@eunbii0213 열심히 피드백 반영해주셨네요! 아래 리뷰 내용을 참고해서 개선하시면 좋을 것 같습니다.

참고로, 현재 기능상에 오류가 있어요. 예를 들어, 초기 상태에서 2호선에서 역삼역을 제거하고, 그 이후에 강남역까지 제거하려 한다면 IndexOutOfBoundsException이 발생하면서 프로그램이 죽어버리네요. 해당 부분은 2개의 역만 남았을 때 노선에서 역을 제거하면 안되는 요구사항을 만족해야 하므로 적절한 에러 메시지와 함께 처리하셔야 합니다!

그리고 전체적으로 for문을 index와 리스트의 size를 이용해 접근하시는 부분이 많습니다. 해당 부분은 모두 `for-each`문으로 교체해주세요. 인덱스를 사용하는 부분은 비즈니스 로직에서 특별한 이유가 없다면 쓰지 않는게 좋습니다.

2022-04-01 12:56 UTC, kth496 commented on src/main/java/subway/Controller.java
> +    public boolean isStationOptionTwoError(User user, Scanner scanner) {
이러한 부분들도 마찬가지로 정확히 무슨 일을 하는지 메서드 이름을 수정해주세요. 지금은 미름만 보면 무슨 일을 하는지 전혀 알 수가 없습니다. 만약 해당 기능의 순서를 바꿔서 2번이 아니라 7번으로 조정된다면 메서드 이름은 아무런 정보를 주지 못하지요. 이름은 기능을 나타내도록 표현해주세요!

2022-04-01 12:56 UTC, kth496 commented on src/main/java/subway/StationView.java
> +        return false;
저번에 드렸던 피드백을 적용하려는 시도는 좋다고 생각합니다! 아직 익숙치 않으셔서 지금은 코드가 조금 난해해진 것 같아요. 현재 StationRepository에서 역을 하나씩 읽어오는 용도로 별도의 getStationFromStations 메서드를 쓰고 계신데요, 사실 이렇게 할 필요는 없습니다. 차라리 Station으로부터 *수정 불가한 읽기전용* 복사본 전체를 받아서 출력하는 것이 더 의미있는 구조가 될 거에요. 단순히 읽기만 할 경우에는 불변 객체를 복사본으로 받아와서 처리하는게 더 깔끔하다는 사실을 기억해주세요! 메시지를 보내는 경우는 상태 변화에 한정하시면 구조잡기 더 수월하실거에요 😃

2022-04-01 12:56 UTC, kth496 commented on src/main/java/subway/View.java
> +        }
앞서 말씀드린 Read-only의 경우에는 그대로 복사본을 꺼내서 쓰시면 되는 부분을 적용하시면 됩니다! 지금은 약간 억지로 코드를 적용하려다보니 for문을 index 기반으로 더 퇴화하고, 코드도 길어졌습니다.

이 경우에는 Line에서 읽기 전용 subwayMap을 반환하는 방법이 적절하겠네요 😃

2022-04-01 12:56 UTC, kth496 commented on src/main/java/subway/domain/InitialBeforeStart.java
> +    }
`initialize`용 데이터를 문자열로 따로 저장하고 초기화에 사용하는것은 비효율적입니다. 직접 객체를 만들어서 초기화하시면 됩니다. 지금의 구조에서는 별 의미 없이 `StringTokenizer`등이 초기화에서 사용되고 있으므로 제거할 수 있다면 제거하는게 좋습니다.

2022-04-02 13:58 UTC, kth496 commented
@eunbii0213 앞서 말씀드린 기능상의 오류는 정확히 확인해보니 없는 역의 이름을 작성했을 때 발생하네요.

아래 로그는 IndexOutOfBoundException이 발생한 상황 로그입니다. 유저가 정상적인 입력을 하지 않았을 경우도 적절히 예외로 잡아서 처리해주시면 됩니다!

```
## 메인 화면
1. 역 관리
2. 노선 관리
3. 구간 관리
4. 지하철 노선도 출력
Q. 종료

## 원하는 기능을 선택하세요.
4

## 지하철 노선도
[INFO] 2호선
[INFO] ---
[INFO] 교대역
[INFO] 강남역
[INFO] 역삼역

[INFO] 3호선
[INFO] ---
[INFO] 교대역
[INFO] 남부터미널역
[INFO] 양재역
[INFO] 매봉역

[INFO] 신분당선
[INFO] ---
[INFO] 강남역
[INFO] 양재역
[INFO] 양재시민의숲역


## 메인 화면
1. 역 관리
2. 노선 관리
3. 구간 관리
4. 지하철 노선도 출력
Q. 종료

## 원하는 기능을 선택하세요.
3

## 구간 관리 화면 
1. 구간 등록
2. 구간 삭제
B. 돌아가기

## 원하는 기능을 선택하세요.
2

## 삭제할 구간의 노선을 입력하세요.
2호선

## 삭제할 구간의 역을 입력하세요.
노량진역
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: -1, Size: 7
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at subway.repository.StationRepository.getStationFromStations(StationRepository.java:19)
	at subway.Controller.isSectionOptionTwoError(Controller.java:76)
	at subway.Controller.whichOptionInSectionManage(Controller.java:112)
	at subway.Controller.sectionManage(Controller.java:103)
	at subway.Controller.startSubwayMap(Controller.java:38)
	at subway.Application.subwayProgramStart(Application.java:34)
	at subway.Application.subwayMap(Application.java:21)
	at subway.Application.main(Application.java:14)

> Task :Application.main() FAILED

FAILURE: Build failed with an exception.
```

2022-04-02 14:13 UTC, kth496 commented on src/main/java/subway/InitialBeforeStart.java
> +    }
Initial 부분에서 의도가 제대로 전달되지 않은 부분에 대해 다시 설명드리고자 합니다.

현재 문제가 되는 부분을 짚어보겠습니다. 초기화 단계가 필요한 Line만 생성해서 Repository에 집어넣는 것이 아니라, **마치 유저의 입력을 재현하는 듯이 작동**한다는 점입니다. 위 코드에서 initialLineNameList는 과연 필요할까요? 사실 저 리스트가 없더라도 다음과 같이 직접 초기화가 가능할 것입니다.

```suggestion
    public void initializeLineRepository() {
        lineRepository.addLine(new Line("2호선"));
        // 이하 동일한 방식으로 역 초기화
    }
```

차이가 느껴지시나요? 지금은 초기화가 아니라, 초기화에 필요한 별도의 정보를 초기화하고, 그것을 이용해 진짜로 초기화하는 로직이 따로 있는 구조입니다. 그리고 그것은 마치 유저가 String을 입력해서 임시 변수에 집어넣은 것처럼 되어있습니다. 그럴 필요가 없이 직접 lineRepository에 넣으시면 됩니다. 그림으로 그려보면 다음과 같습니다.

```
기존로직  : (유저입력) -> (controller) -> (line 생성) -> (lineRepository에 넣음)
초기화로직 :                   (초기화클래스)  -> (line 생성) -> (lineRepository에 넣음)
```

그림에서 겹치는 부분이 보이시나요? 즉, 초기화하는 과정이나 유저가 직접 Line을 생성하는 과정은 사실 하는 일이 동일합니다. 단지 처음 진입하는 부분에서 다를뿐이죠. 이 점을 염두하시고 코드의 중복을 최대한 줄이는 쪽으로 개선해보세요!

이렇게 바꾸려면 현재 구조에서 여러 부분을 수정해야 합니다.

1. 지금은 엄밀히 말해서 Line에 대한 검증이 Line이 아닌 LineRepository에서 이뤄지고 있습니다. 즉, 위에서 제가 제시한 코드를 잘못 작성하면 `new Line("역")`과 같은 초기화가 가능해지는 것이지요. 이를 막기 위해서는 어떻게 해야할까요? 바로 Line의 생성에 대한 검증을 Line의 생성자에게 맡기면 됩니다. 

2. 불필요한 중간 변수들을 제거합니다. (initialLineNameList 등...)

중요하니 한번 더 말씀드리겠습니다. 초기화 단계라 함은 **유저가 미리 입력한 듯이 행동해야하는 것**이 아닙니다. 프로그램의 입장에서 **작동에 필요한 상태를 사전에 구축하는 것**이라고 생각하고 접근하셔야 합니다. 즉, 프로그램의 입장에서 불필요한 과정을 거칠 필요가 없다는 점을 기억하세요!

2022-04-03 13:57 UTC, eunbii0213 commented
선생님, 요구사항 반영하여 수정해보았습니다!
이것저것 지키려고하다보니 코드가 조금 난잡해진 것 같기도하네요 😭
피드백 부탁드립니다!

2022-04-03 17:11 UTC, kth496 commented
@eunbii0213 반영해주신 내용 잘 확인했습니다 ㅎㅎ 이제는 디테일한 부분이 남아있는데 지면으로만 설명하기는 어려우니 화요일에 직접 말씀드리겠습니다 고생하셨어요~!

2022-04-03 17:15 UTC, kth496 commented on src/main/java/subway/InitialBeforeStart.java
> +        LineRepository.getLines(index++).addStationInLine(stationIndex, "역삼역");
getLines의 인자로 인덱스를 직접 전달하고 있네요. Line의 이름으로 찾아내는 방법은 없을까요? 사실 이미 사용하고 계시는데요, 바로 LineRepository의 findLineIndexFromLines 메서드 입니다. 인덱스를 직접 사용하는 방법은 이해하기도 어렵고 실수하기도 매우 쉬운 구조에요. 남은 시간동안은 이것을 어떻게 개선하면 좋을지 고민해보시면 좋겠습니다!

2022-04-11 13:50 UTC, eunbii0213 commented
이번주에 사랑니 발치하느라 빠르게 수정을 못했네요 😭
피드백 부탁드립니다!!

2022-04-14 12:03 UTC, merged